### ISSUE TITLE
pantheon-systems/autotag info found version: 1.3.24 for v1.3.24/linux/amd64

### ISSUE THREAD

**Issue by andreluizmarcelino1** [pantheon-systems/action-autotag#2]
After release 1.3.24 the action stopped working.

pantheon-systems/autotag info checking GitHub for latest tag
pantheon-systems/autotag info found version: 1.3.24 for v1.3.24/linux/amd64
Error: Process completed with exit code 1.

**Comment by pwtyler** [comment]
Hey @andreluizmarcelino1, sorry for the belated followup on this—

We had a failure on the release step of pantheon-systems/autotag starting with 1.3.24, which were resolved with https://github.com/pantheon-systems/autotag/pull/102 & https://github.com/pantheon-systems/autotag/pull/103 (so 1.3.25).

action-autotag has been running for me in projects since that fix, but please re-open if you're still seeing issues.
